apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        
    spec:
      containers:
      - image: {{ default "httpd" .Values.image.repository  }}
        name: {{  .Values.image.repository | default "httpd" | upper }}
