apiVersion: v1
kind: Service
metadata:
  labels:
     app: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}  
status:

