apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-app
  name: db-app
  namespace: jenkins
spec:
  ports:
  - nodePort: 32376
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: db-app
  type: NodePort

