apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db-app
  name: db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db-app
    spec:
      containers:
      - image: httpd
        name: httpd
